#!/bin/bash
#
# god       Startup script for god (http://god.rubyforge.org)
#
# chkconfig: - 85 15
# description: God is an easy to configure, easy to extend monitoring \
#              framework written in Ruby.
#

source /usr/local/rvm/scripts/rvm

rvm use 2.0.0

CONF_DIR=/etc/god

RETVAL=0

# Go no further if config directory is missing.
[ -d "$CONF_DIR" ] || exit 0

case "$1" in
    start)
      # Create pid directory
      god -c $CONF_DIR/master.rb -l /var/log/god.log --log-level debug
      RETVAL=$?
  ;;
    stop)
      god quit
      RETVAL=$?
  ;;
    restart)
      god quit
      god -c $CONF_DIR/master.rb -l /var/log/god.log --log-level debug
      RETVAL=$?
  ;;
    status)
      god status
      RETVAL=$?
  ;;
    *)
      echo "Usage: god {start|stop|restart|status}"
      exit 1
  ;;
esac

exit $RETVAL
